version: '3'
services:
  cromwell:
    image: broadinstitute/cromwell:${CROMWELL_VERSION:-prod}
    command: server
    ports:
    - 8000:8000
    env_file: ./cromwell/mysql.env
    environment:
    - JAVA_OPTS=-Dconfig.file=/etc/cromwell/cromwell.conf
    - GOOGLE_APPLICATION_CREDENTIALS=/root/key.json
    - GOOGLE_AUTH_MODE=${GOOGLE_AUTH_MODE:-application-default}
    - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT:-default-project}
    - GOOGLE_EXECUTIONS_BUCKET
    - DOCKER_HOST=tcp://docker:2375
    - MYSQL_HOST=db
    volumes:
    - ./cromwell/cromwell.conf:/etc/cromwell/cromwell.conf:ro
    - ./docker/${GOOGLE_APPLICATION_CREDENTIALS:-google-nocred}:/root/key.json:ro
    - ./docker/executions:/executions
    # - ./docker/docker-bin:/usr/local/bin:ro
    depends_on:
    - db
    - docker
  db:
    image: mysql
    env_file: ./cromwell/mysql.env
    volumes:
    - ./docker/db:/var/lib/mysql
  docker:
    image: docker:dind
    privileged: true
    volumes:
      # - ./docker/docker-bin:/usr/local/bin
      # - ./docker/docker-run:/var/lib/docker
      - ./docker/executions:/executions
  theia:
    image: quay.io/broadinstitute/wdl-ide-theia
    ports:
    - 3000:3000
    environment:
    - DOCKER_HOST=tcp://docker:2375
    volumes:
    - ./docker/executions:/executions
    - ./docker/home:/home/theia
    depends_on:
    - cromwell
    - docker
